config: configs/clm_cloze_simp.yaml
data_path:
- data/NEG-136-SIMP.tsv
- data/NEG-1500-SIMP-TEMP.tsv
- data/NEG-1500-SIMP-GEN.tsv
model_type:
- CLM
- MAMBA
prompt_template: '{context} {determiner}'
scoring_method: "distribution"
experiment_dir: "experiments/clm_cloze_simp"
batch_size: 1
skip_if_exists: true