batch_size: 8
config: configs/experiment_mlm_nat.yaml
data:
- data/NEG-136-NAT-NT.tsv
- data/NEG-136-NAT-LN.tsv
device: cuda
experiment_dir: experiments/experiment_mlm_nat
model_type:
- MLM
prediction_dir: predictions
prompt_format: '{context}' # removed determiner
save_config: experiment_mlm_nat.yaml
scoring_method: distribution
skip_if_exists: false
topk: 30
