config: configs/mlm_sequence_simp.yaml
data_path:
- data/NEG-136-SIMP.tsv
- data/NEG-1500-SIMP-TEMP.tsv
- data/NEG-1500-SIMP-GEN.tsv
model_type:
- MLM
prompt_template: '{context} {determiner} {target}.'
scoring_method: "sequence_score"
experiment_dir: "experiments/mlm_sequence_simp"
batch_size: 2
skip_if_exists: true