config: configs/iclm_code_sequence_nat.yaml
data_path:
- data/NEG-136-NAT-NT.tsv
- data/NEG-136-NAT-LN.tsv
model_type:
- ICLM
prompt_template: "{context} {target}."
scoring_method: "sequence_score"
experiment_dir: "experiments/iclm_code_sequence_nat"
batch_size: 1
skip_if_exists: true