batch_size: 1
config: configs/nat/experiment_iclm_nat_cloze_prompt.yaml
data:
- data/NEG-136-NAT-NT.tsv
- data/NEG-136-NAT-LN.tsv
device: cuda
experiment_dir: experiments/experiment_iclm_nat_cloze_prompt
model_type:
- ICLM
prediction_dir: predictions
prompt_format: 'Complete the following sentence with ONE word, DO NOT reply with anything other than the answer: "{context} ___." Answer:'
save_config: experiment_iclm_nat_cloze_prompt.yaml
scoring_method: distribution
skip_if_exists: false
topk: 30
