batch_size: 1
config: configs/simp/experiment_clm_simp_cloze_prompt.yaml
data:
- data/NEG-136-SIMP.tsv
- data/NEG-1500-SIMP-GEN.tsv
- data/NEG-1500-SIMP-TEMP.tsv
device: cuda
experiment_dir: experiments/experiment_clm_simp_cloze_prompt
model_type:
- CLM
- MAMBA
prediction_dir: predictions
prompt_format: 'Complete the following sentence with one word: "{context} {determiner} ___."\nAnswer: {determiner}'
save_config: experiment_clm_simp_cloze_prompt.yaml
scoring_method: distribution
skip_if_exists: false
topk: 30
