batch_size: 1
config: configs/simp/experiment_iclm_simp_conditional.yaml
data:
- data/NEG-136-SIMP.tsv
- data/NEG-1500-SIMP-GEN.tsv
- data/NEG-1500-SIMP-TEMP.tsv
device: cuda
experiment_dir: experiments/experiment_iclm_simp_conditional
model_type:
- ICLM
prediction_dir: predictions
prompt_format: '{context} {determiner}'
save_config: experiment_iclm_simp_conditional.yaml
scoring_method: conditional
skip_if_exists: false
topk: 30