batch_size: 8
config: configs/simp/experiment_mlm.yaml
data:
- data/NEG-136-SIMP.tsv
- data/NEG-1500-SIMP-GEN.tsv
- data/NEG-1500-SIMP-TEMP.tsv
device: cuda
experiment_dir: experiments/experiment_mlm
model_type:
- MLM
- SEQ2SEQ
prediction_dir: predictions
prompt_format: '{context} {determiner}'
save_config: experiment_mlm.yaml
scoring_method: distribution
skip_if_exists: false
topk: 30
